config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'
  get 'auth/:provider/callback', to: 'sessions#omniauth'


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  delete '/logout', to: 'sessions#destroy'
  



  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :purchases, only: :index
  resources :comics do 
  resources :purchases, shallow: true     
  end
  resources :users, only: [:new, :create, :show]
  # resources :comics
end
  
# get '/comics/new', to: 'comics#new', as: 'new_comic'
# post '/comics', to: 'comics#create'
# get '/comics/:id', to: 'comics#show', as: 'comic'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
    validates :title, :category, :published, :price, presence: { message: 'dont forget to fill out the fields'}
    validates :price, numericality: { greater_than: 0 }
    validates :title, uniqueness: { scope: [:published, :category], message: "already exist" }
    has_many :purchases, dependent: :destroy 
    has_many :purchasers, through: :purchases, source: :user   #telling it where to look
    belongs_to :user
    accepts_nested_attributes_for :purchases

    def self.search(search)
        if search
          self.where("title LIKE ?", "%#{search}%")
        end
    end
    

    scope :order_by_title, -> { reorder("lower(title) ASC") }

    def title_and_category
        "#{self.title} : #{self.category}"
    end

#     def display_price
#         split_price = self.price.to_s.split(".")
#         if split_price[1].length == 1
#             split_price[1] << "0"
#         elsif split_price[1].length == 0
#             split_price[1] << "00"
#         end
#         display = split_price.join(".")
#         "$#{display}"
#     end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :comic
    belongs_to :user
    validates :purchase_total, :location,  presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
has_many :purchases
has_many :comics, through: :purchases
has_many :comics #user create

has_secure_password

validates :username, :email, presence: true
validates :email, uniqueness: true
# validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
 before_action :set_comic, only: [:show, :edit, :update, :destroy]
 before_action :authorized, only: [:edit, :update, :destroy]
    
 
 def index
          if params[:search]
        @comics = Comic.search(params[:search])
      else
        @comics = Comic.order_by_title
      end
    end

    def show
        # @comic = Comic.find(params[:id])
    end
    
    def new
        @comic = Comic.new
    end

    def create
        @comic = current_user.comics.build(comic_params)
        if @comic.save
            redirect_to comic_path(@comic)
        else
            render :new
        end
    end

    def edit
        # @comic = Comic.find(params[:id])
    end

    def update
    #    @comic = Comic.find(params[:id])
       @comic.update(comic_params) 
       redirect_to comic_path(@comic)
    end

    def destroy
        # @comic = Comic.find(params[:id])
        @comic.destroy
        redirect_to comics_path
    end

    private

    def comic_params
        params.require(:comic).permit(:title, :category, :published, :price, :search)
    end
     
    def set_comic
        unless @comic = Comic.find_by_id(params[:id])
            flash[:message] = 'Comic not found'
            redirect_to comics_path
        end
    end

    def authorized
        if current_user != @comic.user
            flash[:message] = 'Not authorized to edit'
            redirect_to comics_path
        end
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]
  before_action :authorized, only: [:edit, :update, :destroy]
  

    def new
        if params[:comic_id] && @comic = Comic.find_by_id(params[:comic_id])
          @purchase = @comic.purchases.build
        else
          redirect_to root_path, alert: "comic not found"
        end
      end    

    def show
        # @purchase = Purchase.find_by_id(params[:id])
    end
    
    def index
      if params[:comic_id] && @comic = Comic.find_by_id(params[:comic_id])
        @purchases = @comic.purchases
      else
        @purchases = current_user.purchases
    end
  end

    def create
        @comic = Comic.find_by_id(params[:comic_id])
        @purchase = @comic.purchases.build(purchase_params)
        @purchase.user = current_user
        if @purchase.save
          redirect_to purchase_path(@purchase)
        else
          render :new
        end
      end

      def edit

      end

      def update
        @purchase.update(purchase_params) 
        redirect_to purchase_path(@purchase)
 
      end

      def destroy
        @purchase.destroy
        redirect_to purchases_path
      end
    


    private

    def purchase_params
        # byebug
        params.require(:purchase).permit(:location, :purchase_total)     #security measures
    end

    def set_purchase
      @purchase = Purchase.find_by_id(params[:id])
    end

    def authorized
      if current_user != @purchase.user
        flash[:message] = 'Not authorized to edit'
        redirect_to new_comic_purchase_path
        end
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def welcome
  end

  def new
      @user = User.new
  end

  # def create
  #    byebug
  #     if user = User.authenticate(params[:username], params[:password])
  #       session[:current_user_id] = user.id
  #       redirect_to user_path(user) 
  #     else     
  #       redirect_to '/login'
  #     end
  # end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to   '/welcome'     
    else
      flash[:message] = "Incorrect cradentials, please try again"
      redirect_to '/login' 
  end
end

   def destroy
        session.delete(:user_id)
        redirect_to '/login'
   end


      def omniauth
        @user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
          
          u.email = auth['info']['email']
          u.username = auth['info']['name']
          u.password = SecureRandom.hex(10)
        end
          if @user.save
             session[:user_id] = @user.id
             redirect_to  root_path           #new_comic_path
          else
            flash[:message] = user.errors.full_messages.join(", ")
            redirect_to comics_path
          end
      end
  
      private

      def auth
        request.env['omniauth.auth'] 
     end
 
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user

    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    

    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end
    
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

end

app/views/comics/_form.html.erb
<%= render partial: 'layouts/errors', locals: { object: @comic } %>

<%= form_for(@comic) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br><br>
    <%= f.label :category %>
    <%= f.select :category, ['DC', 'MCU'] %><br><br>
    <%= f.label :published %>
    <%= f.select(:published, 1900..2021)  %><br><br>
    <%= f.label :price %>
    <%= f.text_field :price %><br><br>
  
     <%= f.submit %>

    <% end %>

app/views/comics/edit.html.erb
EDIT COMIC<br>
<%= render 'form' %>

app/views/comics/index.html.erb
<h1>All Comics</h1>

<%= form_tag(comics_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
    <% end %>
<% @comics. each do |comic| %>

    <div>
    <%= link_to(comic.title_and_category, comic_path(comic) )%>
    </div>

    <% end %>

app/views/comics/new.html.erb
<h1>Comic World</h1>
<h4>Create Your Comic Here</h4>


<%= render 'form' %>

app/views/comics/show.html.erb
<h1>Your Comic</h1>

<h2><%= @comic.title  %></h2>

<p>Category: <%= @comic.category %></p>

<p>Published: <%= @comic.published %></p>

 <%= number_to_currency(@comic.price) %><br><br> 


 <% if @comic.user == current_user %>
    <%= link_to('edit comic', edit_comic_path(@comic)) %><br>
   <%= link_to('delete comic', @comic, method: 'delete') %><br>
<% end %> 

<%= link_to('purchase comic', new_comic_purchase_path(@comic)) %><br>
<%= link_to('view purchases', comic_purchases_path(@comic)) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<br><br>

<% if flash[:message] %>
<%= flash[:message] %>
<% end %>
<% if logged_in? %>
<%= link_to 'Log Out', logout_path, method: "delete" %> |
<%= link_to("All Comic", comics_path) %> |
<%= link_to("New Comic", new_comic_path) %> |
<%= link_to("Your account", user_path(current_user)) %>


<% else %>
<%= link_to("Login with Google", '/auth/google_oauth2', method: :post) %> 
<h4> <%= link_to 'Log In', '/login' %> or <%= link_to 'Sign Up', '/signup' %> to continue </h4>
<br><br>
<% end %>
 <%= yield %>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= render partial: 'layouts/errors', locals: { object: @purchase } %>

<%= form_for([@comic, @purchase]) do |f| %>
    <%= f.label :location %>
    <%= f.text_field :location %><br><br>
    <%= f.label :purchase_total %>
    <%= f.text_field :purchase_total %><br><br>
    <%= f.submit %>
<% end %>

app/views/purchases/edit.html.erb
<h1> Edit Purchase </h1>
<% render 'form' %>

app/views/purchases/index.html.erb
<h3>All purchases<h3>

<% @purchases.each do |purchase| %>

    <div>
    <%= purchase.comic.title %> $<%= link_to(purchase.purchase_total, purchase_path(purchase) )%>  

    </div>
    <% end %>
    <br>
    <%= link_to("Your Profile", user_path(current_user)) %>

app/views/purchases/new.html.erb
<h1>Purchases</h1>
<%= render partial: 'layouts/errors', locals: {object: @purchase} %>
<%= render 'form' %>

app/views/purchases/show.html.erb
<br><br>
<h3><%= @purchase.comic.title %></h3>
<h3><%= @purchase.location %></h3>
<%= number_to_currency(@purchase.purchase_total) %><br>


<br><% if @purchase.user == current_user %><br>
<%= link_to('edit purchase', edit_purchase_path(@purchase)) %><br>
<%= link_to('delete purchase', purchase_path(@purchase), method: 'delete') %><br>
<% end %>
<%= link_to("Your account", user_path(current_user)) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render partial: 'layouts/errors', locals: {object: @user} %>
<%= form_for(@user) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    
    <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<br>
<%= link_to("All Comic", comics_path) %> |
<%= link_to("New Comic", new_comic_path) %> <br>
<h1>Welcome <%= @user.username %></h1>
<h3><%= link_to("View your purchases", purchases_path) %></h3>